//! Human-readable stock-engine interoperability reporting from validated bundles.

use std::fmt::Write;

use anyhow::{bail, Context, Result};
use catalog_bench_common::contract::{AssertionOutcome, EvidenceId, Provenance, ResultOutcome};

use crate::matrix::{display_version, markdown_text, outcome_label, published_path};
use crate::{ValidatedBundle, ValidatedResult};

const ENGINE_SCENARIO_ID: &str = "engine.iceberg.write-read-evolution";
const ENGINE_SCENARIO_VERSION: u32 = 1;
const TRANSCRIPT_EVIDENCE_ID: &str = "engine-transcript";

/// Render a correctness matrix exclusively from validated stock-engine results.
pub fn render_engine_matrix(bundle: &ValidatedBundle) -> Result<String> {
    let scenario = bundle
        .scenarios()
        .first()
        .context("engine matrix requires one scenario")?;
    if bundle.scenarios().len() != 1
        || scenario.scenario().id.as_str() != ENGINE_SCENARIO_ID
        || scenario.scenario().version != ENGINE_SCENARIO_VERSION
    {
        bail!("engine matrix requires the stock-engine interoperability v1 scenario");
    }

    let mut results = bundle.results().iter().collect::<Vec<_>>();
    results.sort_by(|left, right| {
        left.result()
            .catalog
            .profile_component
            .cmp(&right.result().catalog.profile_component)
    });
    if results.is_empty() {
        bail!("engine matrix requires at least one result");
    }

    let mut output = String::new();
    writeln!(
        output,
        "<!-- Generated by catalog-bench-contract; edit reviewed evidence, not this file. -->\n"
    )?;
    writeln!(output, "# {}\n", markdown_text(&bundle.manifest().title))?;
    write_provenance(&mut output, bundle)?;
    writeln!(
        output,
        "Scenario: `{}` v{} · profile: `{}` · [manifest](manifest.json).\n",
        scenario.scenario().id,
        scenario.scenario().version,
        bundle.profile().id
    )?;
    writeln!(
        output,
        "This is an interoperability correctness matrix, not a latency or throughput ranking. Catalogs are listed by stable profile ID; `pass`, `fail`, `unsupported`, and `not-tested` remain distinct.\n"
    )?;
    writeln!(
        output,
        "| Catalog | Stock engine | Outcome | Required assertions | Result | Transcript |"
    )?;
    writeln!(output, "|---|---|:---:|:---:|:---:|:---:|")?;
    for result in &results {
        write_summary_row(&mut output, result)?;
    }

    writeln!(output, "\n## Assertion matrix\n")?;
    write!(output, "| Required assertion |")?;
    for result in &results {
        write!(
            output,
            " {} |",
            markdown_text(&result.result().catalog.name)
        )?;
    }
    writeln!(output)?;
    write!(output, "|---|")?;
    for _ in &results {
        write!(output, ":---:|")?;
    }
    writeln!(output)?;
    for assertion in &scenario.scenario().assertions {
        if !assertion.required {
            continue;
        }
        write!(output, "| `{}` |", assertion.id)?;
        for result in &results {
            let cell = result
                .result()
                .assertions
                .iter()
                .find(|evaluation| evaluation.assertion == assertion.id)
                .map(|evaluation| assertion_symbol(&evaluation.outcome))
                .unwrap_or("—");
            write!(output, " {cell} |")?;
        }
        writeln!(output)?;
    }

    let non_pass = results
        .iter()
        .filter(|result| !matches!(result.result().outcome, ResultOutcome::Pass { .. }))
        .copied()
        .collect::<Vec<_>>();
    if !non_pass.is_empty() {
        writeln!(output, "\n## Non-pass outcomes\n")?;
        for result in non_pass {
            write_non_pass(&mut output, result)?;
        }
    }

    writeln!(output, "## Evidence\n")?;
    writeln!(
        output,
        "The manifest and referenced records bind exact profile, scenario, review, and sanitized transcript bytes; pinned source/image identities; execution environment; every assertion outcome; and redaction review. Regenerate this matrix only from the validated bundle:\n"
    )?;
    writeln!(output, "```sh")?;
    writeln!(
        output,
        "cargo run -p catalog-bench-contract --locked -- matrix check \\"
    )?;
    let manifest_path = published_path(bundle.manifest_path());
    let matrix_path = manifest_path.with_file_name("MATRIX.md");
    writeln!(output, "  --manifest {} \\", manifest_path.display())?;
    writeln!(output, "  --output {}", matrix_path.display())?;
    writeln!(output, "```")?;
    Ok(output)
}

fn write_provenance(output: &mut String, bundle: &ValidatedBundle) -> Result<()> {
    match &bundle.manifest().provenance {
        Provenance::LiveRun {
            started_at,
            completed_at,
            ..
        } => writeln!(
            output,
            "Live four-catalog run from `{started_at}` through `{completed_at}`.\n"
        )?,
        Provenance::HistoricalImport {
            source_date,
            explanation,
            ..
        } => writeln!(
            output,
            "Historical import of {source_date}: {}\n",
            markdown_text(explanation)
        )?,
        Provenance::Fixture { explanation } => {
            writeln!(output, "Fixture bundle: {}\n", markdown_text(explanation))?
        }
    }
    Ok(())
}

fn write_summary_row(output: &mut String, result: &ValidatedResult) -> Result<()> {
    let record = result.result();
    let engine = record
        .client
        .as_ref()
        .context("engine interoperability result omits its stock engine")?;
    let (passed, failed, not_evaluated) = assertion_counts(result);
    let required = passed + failed + not_evaluated;
    let assertion_summary = if failed == 0 && not_evaluated == 0 {
        format!("{passed} / {required} passed")
    } else if not_evaluated == required {
        "not evaluated".to_owned()
    } else {
        format!("{passed} passed, {failed} failed, {not_evaluated} not evaluated")
    };
    let transcript = evidence_location(result, TRANSCRIPT_EVIDENCE_ID)?;
    writeln!(
        output,
        "| {} {} | {} {} | `{}` | {} | [record]({}) | [evidence]({}) |",
        markdown_text(&record.catalog.name),
        markdown_text(display_version(&record.catalog.version)),
        markdown_text(&engine.name),
        markdown_text(display_version(&engine.version)),
        outcome_label(&record.outcome),
        assertion_summary,
        result.artifact().location,
        transcript
    )?;
    Ok(())
}

fn assertion_counts(result: &ValidatedResult) -> (usize, usize, usize) {
    result
        .result()
        .assertions
        .iter()
        .filter(|evaluation| evaluation.required)
        .fold(
            (0, 0, 0),
            |(passed, failed, skipped), evaluation| match evaluation.outcome {
                AssertionOutcome::Pass => (passed + 1, failed, skipped),
                AssertionOutcome::Fail { .. } => (passed, failed + 1, skipped),
                AssertionOutcome::NotEvaluated { .. } => (passed, failed, skipped + 1),
            },
        )
}

fn assertion_symbol(outcome: &AssertionOutcome) -> &'static str {
    match outcome {
        AssertionOutcome::Pass => "pass",
        AssertionOutcome::Fail { .. } => "**fail**",
        AssertionOutcome::NotEvaluated { .. } => "not evaluated",
    }
}

fn evidence_location<'a>(result: &'a ValidatedResult, id: &str) -> Result<&'a str> {
    result
        .result()
        .evidence
        .iter()
        .find(|evidence| evidence.id == EvidenceId::from(id))
        .map(|evidence| evidence.artifact.location.as_str())
        .with_context(|| format!("result `{}` omits evidence `{id}`", result.result().id))
}

fn write_non_pass(output: &mut String, result: &ValidatedResult) -> Result<()> {
    let record = result.result();
    writeln!(
        output,
        "### {} {} — `{}`\n",
        markdown_text(&record.catalog.name),
        markdown_text(display_version(&record.catalog.version)),
        outcome_label(&record.outcome)
    )?;
    match &record.outcome {
        ResultOutcome::Fail { failure } => {
            writeln!(
                output,
                "{}\n\n{}\n",
                markdown_text(&failure.summary),
                markdown_text(&failure.detail)
            )?;
        }
        ResultOutcome::Unsupported { limitation } => {
            writeln!(
                output,
                "Unsupported capability `{}`: {}\n",
                limitation.capability,
                markdown_text(&limitation.explanation)
            )?;
        }
        ResultOutcome::NotTested { reason } => {
            writeln!(
                output,
                "Not tested: {}\n",
                markdown_text(&reason.explanation)
            )?;
        }
        ResultOutcome::Pass { .. } => unreachable!("filtered before rendering"),
    }
    Ok(())
}
