use std::fmt::Write;
use std::path::{Component, Path, PathBuf};

use anyhow::{bail, Context, Result};
use catalog_bench_common::contract::{
    Metric, MetricValue, Provenance, ResultOutcome, ResultRecord,
};

use crate::ValidatedBundle;

/// Select the scenario-specific renderer for one validated result bundle.
pub fn render_matrix(bundle: &ValidatedBundle) -> Result<String> {
    let scenario = bundle
        .scenarios()
        .first()
        .context("matrix requires one scenario")?;
    if bundle.scenarios().len() != 1 {
        bail!("matrix requires exactly one scenario");
    }
    match scenario.scenario().id.as_str() {
        "iceberg-rest.commit.same-table-contention" => render_commit_matrix(bundle),
        "engine.iceberg.write-read-evolution" => crate::engine_matrix::render_engine_matrix(bundle),
        id => bail!("no matrix renderer is registered for scenario `{id}`"),
    }
}

/// Render a commit matrix exclusively from validated result records.
pub fn render_commit_matrix(bundle: &ValidatedBundle) -> Result<String> {
    if bundle.scenarios().len() != 1 {
        bail!(
            "commit matrix requires exactly one scenario, found {}",
            bundle.scenarios().len()
        );
    }

    let mut pass_rows = bundle
        .results()
        .iter()
        .filter(|record| matches!(&record.result().outcome, ResultOutcome::Pass { .. }))
        .map(|record| {
            Ok((
                record,
                throughput(record.result())?,
                sequential_p50(record.result())?,
            ))
        })
        .collect::<Result<Vec<_>>>()?;
    pass_rows.sort_by(
        |(left, left_throughput, left_latency), (right, right_throughput, right_latency)| {
            right_throughput
                .total_cmp(left_throughput)
                .then_with(|| left_latency.total_cmp(right_latency))
                .then_with(|| {
                    left.result()
                        .catalog
                        .profile_component
                        .cmp(&right.result().catalog.profile_component)
                })
        },
    );
    let mut non_pass_rows = bundle
        .results()
        .iter()
        .filter(|record| !matches!(&record.result().outcome, ResultOutcome::Pass { .. }))
        .collect::<Vec<_>>();
    non_pass_rows
        .sort_by(|left, right| left.result().catalog.name.cmp(&right.result().catalog.name));

    let mut output = String::new();
    writeln!(
        output,
        "<!-- Generated by catalog-bench-contract; edit result records, not this file. -->\n"
    )?;
    writeln!(output, "# {}\n", bundle.manifest().title)?;
    match &bundle.manifest().provenance {
        Provenance::HistoricalImport {
            source_date,
            explanation,
            ..
        } => writeln!(
            output,
            "This is a **historical import** of the {source_date} evidence, not a new live run. {}\n",
            markdown_text(explanation)
        )?,
        Provenance::LiveRun {
            started_at,
            completed_at,
            ..
        } => writeln!(
            output,
            "Live run from `{started_at}` through `{completed_at}`.\n"
        )?,
        Provenance::Fixture { explanation } => writeln!(
            output,
            "Fixture bundle: {}\n",
            markdown_text(explanation)
        )?,
    }
    writeln!(
        output,
        "Scenario: `{}` v{} · profile: `{}` · [manifest](manifest.json).\n",
        bundle.scenarios()[0].scenario().id,
        bundle.scenarios()[0].scenario().version,
        bundle.profile().id
    )?;
    writeln!(
        output,
        "Numeric ranks include only `pass` outcomes and sort by median accepted concurrent throughput. Failed, unsupported, and not-tested rows retain any available diagnostic measurements but are never ranked.\n"
    )?;
    writeln!(
        output,
        "| Rank | Catalog | Outcome | Valid rounds | Concurrent accepted | Sequential accepted | Sequential p50 | Sequential p99 | Conflict rate | Error rate | Errors |"
    )?;
    writeln!(
        output,
        "|:---:|---|:---:|:---:|---:|---:|---:|---:|---:|---:|---:|"
    )?;

    for (index, (record, _, _)) in pass_rows.iter().enumerate() {
        write_row(&mut output, &(index + 1).to_string(), record.result(), true)?;
    }
    for record in &non_pass_rows {
        write_row(&mut output, "—", record.result(), false)?;
    }

    if !non_pass_rows.is_empty() {
        writeln!(output, "\n## Non-pass outcomes\n")?;
        for record in non_pass_rows {
            writeln!(
                output,
                "### {} {} — `{}`\n",
                markdown_text(&record.result().catalog.name),
                markdown_text(display_version(&record.result().catalog.version)),
                outcome_label(&record.result().outcome)
            )?;
            match &record.result().outcome {
                ResultOutcome::Fail { failure } => {
                    writeln!(output, "{}\n\n{}\n", failure.summary, failure.detail)?;
                }
                ResultOutcome::Unsupported { limitation } => {
                    writeln!(
                        output,
                        "Unsupported capability `{}`: {}\n",
                        limitation.capability, limitation.explanation
                    )?;
                }
                ResultOutcome::NotTested { reason } => {
                    writeln!(output, "Not tested: {}\n", reason.explanation)?;
                }
                ResultOutcome::Pass { .. } => unreachable!("filtered above"),
            }
        }
    }

    writeln!(output, "## Evidence\n")?;
    writeln!(
        output,
        "All artifact sizes, SHA-256 hashes, exact source/image identities, environment-capture gaps, assertion outcomes, and round-selection rules are in [the manifest](manifest.json) and its referenced records. The matrix is reproducible with:\n"
    )?;
    writeln!(output, "```sh")?;
    writeln!(
        output,
        "cargo run -p catalog-bench-contract --locked -- matrix check \\"
    )?;
    let manifest_path = published_path(bundle.manifest_path());
    let matrix_path = manifest_path.with_file_name("MATRIX.md");
    writeln!(output, "  --manifest {} \\", manifest_path.display())?;
    writeln!(output, "  --output {}", matrix_path.display())?;
    writeln!(output, "```")?;
    Ok(output)
}

fn write_row(
    output: &mut String,
    rank: &str,
    result: &ResultRecord,
    require_measurements: bool,
) -> Result<()> {
    let concurrent = format_distribution_metric(
        result,
        "concurrent",
        "successful-throughput",
        "/s",
        1,
        require_measurements,
    )?;
    let sequential = format_distribution_metric(
        result,
        "sequential",
        "successful-throughput",
        "/s",
        1,
        require_measurements,
    )?;
    let p50 = format_distribution_metric(
        result,
        "sequential",
        "p50-latency",
        " ms",
        3,
        require_measurements,
    )?;
    let p99 = format_distribution_metric(
        result,
        "sequential",
        "p99-latency",
        " ms",
        3,
        require_measurements,
    )?;
    let conflict = format_distribution_metric(
        result,
        "concurrent",
        "conflict-rate",
        "%",
        3,
        require_measurements,
    )?;
    let error_rate = format_distribution_metric(
        result,
        "concurrent",
        "error-rate",
        "%",
        3,
        require_measurements,
    )?;
    let valid_rounds = format_valid_rounds(result, require_measurements)?;
    let errors =
        format_counter_metric(result, "concurrent", "request-errors", require_measurements)?;
    writeln!(
        output,
        "| {rank} | {} {} | `{}` | {valid_rounds} | {concurrent} | {sequential} | {p50} | {p99} | {conflict} | {error_rate} | {errors} |",
        markdown_text(&result.catalog.name),
        markdown_text(display_version(&result.catalog.version)),
        outcome_label(&result.outcome)
    )?;
    Ok(())
}

fn throughput(result: &ResultRecord) -> Result<f64> {
    distribution_metric(result, "concurrent", "successful-throughput").and_then(distribution_median)
}

fn sequential_p50(result: &ResultRecord) -> Result<f64> {
    distribution_metric(result, "sequential", "p50-latency").and_then(distribution_median)
}

fn format_distribution_metric(
    result: &ResultRecord,
    phase: &str,
    name: &str,
    suffix: &str,
    precision: usize,
    required: bool,
) -> Result<String> {
    let Some(distribution) = optional_distribution_metric(result, phase, name)? else {
        return missing_metric(result, phase, name, required);
    };
    let median = distribution_median(distribution)?;
    Ok(format!(
        "{median:.precision$}{suffix} ({min:.precision$}–{max:.precision$})",
        min = distribution.minimum,
        max = distribution.maximum
    ))
}

fn distribution_metric<'a>(
    result: &'a ResultRecord,
    phase: &str,
    name: &str,
) -> Result<&'a catalog_bench_common::contract::Distribution> {
    optional_distribution_metric(result, phase, name)?
        .with_context(|| format!("result `{}` has no `{phase}.{name}` metric", result.id))
}

fn optional_distribution_metric<'a>(
    result: &'a ResultRecord,
    phase: &str,
    name: &str,
) -> Result<Option<&'a catalog_bench_common::contract::Distribution>> {
    let Some(metric) = metric(result, phase, name) else {
        return Ok(None);
    };
    match &metric.value {
        MetricValue::Distribution { distribution } => Ok(distribution),
        value => bail!("metric `{phase}.{name}` is not a distribution: {value:?}"),
    }
    .map(Some)
}

fn distribution_median(distribution: &catalog_bench_common::contract::Distribution) -> Result<f64> {
    distribution
        .quantiles
        .get("p50")
        .copied()
        .context("distribution has no p50")
}

fn optional_counter_metric(result: &ResultRecord, phase: &str, name: &str) -> Result<Option<u64>> {
    let Some(metric) = metric(result, phase, name) else {
        return Ok(None);
    };
    match &metric.value {
        MetricValue::Counter { value } => Ok(Some(*value)),
        value => bail!("metric `{phase}.{name}` is not a counter: {value:?}"),
    }
}

fn metric<'a>(result: &'a ResultRecord, phase: &str, name: &str) -> Option<&'a Metric> {
    result
        .measurements
        .iter()
        .find(|measurement| measurement.name == phase)?
        .metrics
        .iter()
        .find(|metric| metric.name == name)
}

fn format_valid_rounds(result: &ResultRecord, required: bool) -> Result<String> {
    let valid = optional_counter_metric(result, "concurrent", "valid-rounds")?;
    let measured = optional_counter_metric(result, "concurrent", "measured-rounds")?;
    match (valid, measured) {
        (Some(valid), Some(measured)) => Ok(format!("{valid} / {measured}")),
        (None, None) => missing_metric(result, "concurrent", "valid/measured-rounds", required),
        _ => bail!(
            "result `{}` must provide both valid-rounds and measured-rounds",
            result.id
        ),
    }
}

fn format_counter_metric(
    result: &ResultRecord,
    phase: &str,
    name: &str,
    required: bool,
) -> Result<String> {
    optional_counter_metric(result, phase, name)?.map_or_else(
        || missing_metric(result, phase, name, required),
        |value| Ok(value.to_string()),
    )
}

fn missing_metric(
    result: &ResultRecord,
    phase: &str,
    name: &str,
    required: bool,
) -> Result<String> {
    if required {
        bail!(
            "ranked result `{}` has no `{phase}.{name}` metric",
            result.id
        );
    }
    Ok("—".to_owned())
}

pub(crate) fn outcome_label(outcome: &ResultOutcome) -> &'static str {
    match outcome {
        ResultOutcome::Pass { .. } => "pass",
        ResultOutcome::Fail { .. } => "fail",
        ResultOutcome::Unsupported { .. } => "unsupported",
        ResultOutcome::NotTested { .. } => "not-tested",
    }
}

pub(crate) fn markdown_text(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

pub(crate) fn display_version(version: &str) -> &str {
    if version.len() == 40 && version.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        &version[..8]
    } else {
        version
    }
}

pub(crate) fn published_path(path: &Path) -> PathBuf {
    let components = path.components().collect::<Vec<_>>();
    let Some(results_index) = components.iter().rposition(
        |component| matches!(component, Component::Normal(value) if *value == "results"),
    ) else {
        return path.to_owned();
    };
    components[results_index..]
        .iter()
        .fold(PathBuf::new(), |mut relative, component| {
            relative.push(component.as_os_str());
            relative
        })
}
